### ISSUE TITLE
Outdated endpoints

### ISSUE THREAD

**Issue by GwenHarrison** [singer-io/tap-frontapp#19]
This app does not appear to use use the latest front core api: https://dev.frontapp.com/changelog/core-api-analytics-and-exports-updates

**Comment by jjspratt** [comment]
Yes, attempting to setup a new integration via stitch is not possible due to this conflict. It appears there has been a pull request awaiting a review since February. 

It appears this tap has either been abandoned or there aren't any reviewers comfortable with frontapp to evaluate the pr.

**Comment by rdeshmukh15** [comment]
Released the changes with the valid endpoints in (#22)
